name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Ubuntu:
    name: 'Ubuntu (${{ matrix.python }}${{ matrix.extra_name }})'
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - 'pypy-3.7'
          - 'pypy-3.8'
          - 'pypy-3.9'
        check_lint: ['0']
        extra_name: ['']
        include:
          - python: '3.9'
            check_lint: '1'
            extra_name: ', check lint'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ fromJSON(format('["{0}", "{1}"]', format('{0}.0-alpha - {0}.X', matrix.python), matrix.python))[startsWith(matrix.python, 'pypy')] }}
      - name: Run tests
        run: ./ci.sh
        env:
          CHECK_LINT: '${{ matrix.check_lint }}'
          # Should match 'name:' up above
          JOB_NAME: 'Ubuntu (${{ matrix.python }}${{ matrix.extra_name }})'
